[package]
name = "simple_core"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "=0.9.31"
# bootloader_api = "0.9.8"
x86_64 = "0.15.2"
